name: Fly Deploy Private Location
on:
  push:
    branches:
      - main
    paths:
      - "apps/private-location/**"
      - "apps/checker/**"
jobs:
  deploy-private-location:
    name: Deploy Private Location
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - working-directory: apps/private-location
        name: Deploy Private Location
        run: |
          flyctl deploy --remote-only --wait-timeout=500
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
